export const HELPER_CHANNEL = 'helper_function'

export const STATUS_INSTALLED = 'installed'
export const STATUS_NOT_INSTALLED = 'not_installed'
export const STATUS_DOWNLOADING = 'downloading'
export const STATUS_PAUSED_DOWNLOADING = 'paused_downloading'
export const STATUS_RUNNING = 'application_running'

export const QUERY_INSTALLED = 'query_installed_applications'
export const QUERY_MANIFEST_APP = 'query_manifest_app'

export const APPLICATION_IMPORT = 'import_application'
export const APPLICATION_IMAGE_SET = 'set_application_image'
export const APPLICATION_LAUNCH = 'launch_application'
export const APPLICATION_STOP = 'stop_application'
export const APPLICATION_DOWNLOAD = 'download_application'
export const APPLICATION_PAUSE_DOWNLOAD = 'pause_download_application'
export const APPLICATION_RESUME_DOWNLOAD = 'resume_download_application'
export const APPLICATION_DELETE = 'delete_application'
export const APPLICATION_PARAMETERS = 'launch_parameters'
export const APPLICATION_AUTOSTART = 'autostart_application'
export const APPLICATION_SCHEDULER = 'schedule_application'

export const CONFIG_APPLICATION_RETURN = 'application_config'
export const CONFIG_APPLICATION_SET = 'set_config_application'
export const CONFIG_APPLICATION_GET = 'get_config_application'
export const CONFIG_APPLICATION_STEAMCMD = 'config_steamcmd'
