export const QUERY_INSTALLED = 'query_installed_applications'
export const QUERY_MANIFEST_APP = 'query_manifest_app'
export const SCAN_MANIFEST = 'scan_manifest'
export const CHECK_REMOTE_CONFIG = 'check_remote_config'

export const VR_MANIFEST = 'edit_vr_manifest'

export const APPLICATION_IMPORT = 'import_application'
export const APPLICATION_IMAGE_SET = 'set_application_image'
export const APPLICATION_LAUNCH = 'launch_application'
export const APPLICATION_STOP = 'stop_application'
export const APPLICATION_DOWNLOAD = 'download_application'
export const APPLICATION_PAUSE_DOWNLOAD = 'pause_download_application'
export const APPLICATION_RESUME_DOWNLOAD = 'resume_download_application'
export const APPLICATION_DELETE = 'delete_application'
export const APPLICATION_PARAMETERS = 'launch_parameters'
export const APPLICATION_SET_PARAMETERS = 'parameter_application'
export const APPLICATION_SCHEDULER = 'schedule_application'

export const CONFIG_LAUNCHER = 'configure_launcher'
export const CONFIG_APPLICATION_RETURN = 'application_config'
export const CONFIG_APPLICATION_SET = 'set_config_application'
export const CONFIG_APPLICATION_GET = 'get_config_application'
export const CONFIG_APPLICATION_STEAMCMD = 'config_steamcmd'

export const SET_REMOTE_CONFIG = 'set_remote_config'
export const UPLOAD_EXISTING_CONFIG = 'upload_existing_conifg'
