version: 2.1

orbs:
  windows: circleci/windows@5.0.0

commands:
  clone_hosting:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:dc:58:24:df:b4:3f:8e:66:69:b9:9c:3b:73:2e:3e"
      - run:
          name: Setup git config
          command: git config --global user.name "CircleCI" && git config --global user.email "CircleCI@lumination.com.au"
      - run:
          name: Add github to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Add github to known hosts
          command: dir /home/circleci/.ssh
      - run:
          name: Write ssh config file
          command: echo "Host github.com" > ~/.ssh/config && echo "  IdentitiesOnly yes" >> ~/.ssh/config && echo "  IdentityFile /home/circleci/.ssh/id_rsa_bddc5824dfb43f8e6669b99c3b732e3e" >> ~/.ssh/config
      - run:
          name: Clone hosting server
          command: cd ~/ && git clone git@github.com:LuminationDev/LeadMeLabs-Launcher-Hosting.git

  copy_and_push:
    parameters:
      branch:
        type: string
    steps:
      - run:
          name: Checkout <<parameters.branch>>
          command: cd ~/LeadMeLabs-Launcher-Hosting && git checkout <<parameters.branch>>
      - run:
          name: Delete old files
          command: rm -rf ~/LeadMeLabs-Launcher-Hosting/applications/config-tool
      - run:
          name: Copy built files to git repository
          command: cp -r ./project/dist ~/LeadMeLabs-Launcher-Hosting/applications/electron-launcher
      - run:
          name: Add built files to git
          command: cd ~/LeadMeLabs-Launcher-Hosting/applications/electron-launcher && git add --all
      - run:
          name: Commit
          command: cd ~/LeadMeLabs-Launcher-Hosting && git commit -m "Update launcher"
      - run:
          name: Push
          command: cd ~/LeadMeLabs-Launcher-Hosting && git push

  windows-npm:
    steps:
      - run: choco install wget -y
      - run:
         command: wget https://nodejs.org/dist/v16.17.0/node-v16.17.0-x86.msi -P C:\Users\circleci\Downloads\
         shell: cmd.exe
      - run: MsiExec.exe /i C:\Users\circleci\Downloads\node-v16.17.0-x86.msi /qn
      - run:
          command: |
              Start-Process powershell -verb runAs -Args "-start GeneralProfile"
              nvm install 16.17.0
              nvm use 16.17.0

  build:
    parameters:
      buildType:
        type: string
      command:
        type: string
    steps:
      - checkout
      - run:
          name: "npm ci"
          command: "npm ci"
      - run:
          name: "build"
          command: "npm run build"
      - run:
          name: "electron-build"
          command: "npm run electron-build -- -<<parameters.command>>"
      - when:
          condition:
            and:
              - equal: [w, <<parameters.command>>]
          steps:
            - run: rm ~/project/dist/builder-debug.yml
            - run: rm ~/project/dist/win-unpacked/LeadMe.exe
      - store_artifacts:
          path: ~/project/dist
      - persist_to_workspace:
          root: ~/
          paths:
            - project/dist

jobs:
  run-tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
      - run:
          name: Run tests
          command: |
            npm test
  build-windows:
    executor:
      name: windows/default
    parameters:
      buildType:
        type: string
    steps:
      - windows-npm
      - build:
          buildType: <<parameters.buildType>>
          command: w

  commit-and-push:
    parameters:
      branch:
        type: string
    docker:
      - image: cimg/node:current
    steps:
      - clone_hosting
      - attach_workspace:
          at: ./
      - copy_and_push:
          branch: <<parameters.branch>>

workflows:
  build_release:
    jobs:
      - hold:
          context: LeadMeDeployers
          type: approval
          filters:
            branches:
              only:
                - main
      - build-windows:
          buildType: "Release"
          requires:
            - hold
      - commit-and-push:
          branch: "main"
          requires:
            - build-windows
