version: 2.1

orbs:
  windows: circleci/windows@5.0.0

commands:
  clone_hosting:
    parameters:
      buildType:
        type: string
    steps:
      - add_ssh_keys:
          fingerprints:
            - "12:41:3e:8a:8f:e0:54:05:f1:4c:a3:85:0b:49:1b:c8"
            - "56:0c:4f:e9:f6:44:2d:cc:ea:78:cb:bf:fe:56:be:b5"
      - run:
          name: Setup git config
          command: git config --global user.name "CircleCI" && git config --global user.email "CircleCI@lumination.com.au"
      - run:
          name: Add github to known hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Add github to known hosts
          command: dir /home/circleci/.ssh
      - when:
          condition:
            and:
              - equal: [Development, <<parameters.buildType>>]
          steps:
            - run:
                name: Write ssh config file
                command: echo "Host github.com" > ~/.ssh/config && echo "  IdentitiesOnly yes" >> ~/.ssh/config && echo "  IdentityFile /home/circleci/.ssh/id_rsa_560c4fe9f6442dccea78cbbffe56beb5" >> ~/.ssh/config
            - run:
                name: Clone hosting server
                command: cd ~/ && git clone git@github.com:LuminationDev/LeadMeLabs-Launcher-Hosting-Development.git
      - when:
          condition:
            and:
              - equal: [Release, <<parameters.buildType>> ]
          steps:
            - run:
                name: Write ssh config file
                command: echo "Host github.com" > ~/.ssh/config && echo "  IdentitiesOnly yes" >> ~/.ssh/config && echo "  IdentityFile /home/circleci/.ssh/id_rsa_12413e8a8fe05405f14ca3850b491bc8" >> ~/.ssh/config
            - run:
                name: Clone hosting server
                command: cd ~/ && git clone git@github.com:LuminationDev/LeadMeLabs-Launcher-Hosting.git

  copy_and_push:
    parameters:
      branch:
        type: string
      repository:
        type: string
    steps:
      - run:
          name: Checkout <<parameters.branch>>
          command: cd ~/<<parameters.repository>> && git checkout <<parameters.branch>>
      - run: ls ~/<<parameters.repository>>/applications/electron-launcher
      - run:
          name: Delete old files
          command: rm -rf ~/LeadMeLabs-Launcher-Hosting/applications/electron-launcher
      - run: ls ~/<<parameters.repository>>/applications/electron-launcher
      - run:
          name: Copy built files to git repository
          command: cp -r ./project/dist/. ~/<<parameters.repository>>/applications/electron-launcher
      - run:
          name: Add built files to git
          command: cd ~/<<parameters.repository>>/applications/electron-launcher && git add --all
      - run: ls ~/<<parameters.repository>>/applications/electron-launcher
      - run:
          name: Commit
          command: cd ~/<<parameters.repository>> && git commit -m "Update launcher"
      - run: ls ~/<<parameters.repository>>
      - run:
          name: Push
          command: cd ~/<<parameters.repository>> && git push

  windows-npm:
    steps:
      - run: choco install wget -y
      - run:
         command: wget https://nodejs.org/dist/v16.17.0/node-v16.17.0-x86.msi -P C:\Users\circleci\Downloads\
         shell: cmd.exe
      - run: MsiExec.exe /i C:\Users\circleci\Downloads\node-v16.17.0-x86.msi /qn
      - run:
          command: |
              Start-Process powershell -verb runAs -Args "-start GeneralProfile"
              nvm install 16.17.0
              nvm use 16.17.0

  build:
    parameters:
      command:
        type: string
    steps:
      - checkout
      - run:
          name: "npm ci"
          command: "npm ci"
      - run:
          name: "build"
          command: "npm run build"
      - run:
          name: "electron-build"
          command: "npm run electron-build -- -<<parameters.command>>"
      - when:
          condition:
            and:
              - equal: [w, <<parameters.command>>]
          steps:
            - run: rm ~/project/dist/builder-debug.yml
            - run: rm ~/project/dist/win-unpacked/LeadMe.exe
      - store_artifacts:
          path: ~/project/dist
      - persist_to_workspace:
          root: ~/
          paths:
            - project/dist

jobs:
  run-tests:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci
      - run:
          name: Run tests
          command: |
            npm test
  build-windows:
    executor:
      name: windows/default
    steps:
      - windows-npm
      - build:
          command: w

  commit-and-push:
    parameters:
      branch:
        type: string
      repository:
        type: string
      buildType:
        type: string
    docker:
      - image: cimg/node:current
    steps:
      - clone_hosting:
          buildType: <<parameters.buildType>>
      - attach_workspace:
          at: ./
      - copy_and_push:
          branch: <<parameters.branch>>
          repository: <<parameters.repository>>

workflows:
  build_release:
    jobs:
      - hold:
          context: LeadMeDeployers
          type: approval
          filters:
            branches:
              only:
                - main
      - build-windows:
          requires:
            - hold
      - commit-and-push:
          branch: "main"
          buildType: "Release"
          repository: "LeadMeLabs-Launcher-Hosting"
          requires:
            - build-windows
  build_development:
    jobs:
      - hold:
          context: LeadMeDeployers
          type: approval
      - build-windows:
          requires:
            - hold
      - commit-and-push:
          branch: "main"
          buildType: "Development"
          repository: "LeadMeLabs-Launcher-Hosting-Development"
          requires:
            - build-windows
